### ISSUE TITLE
"Could not decrypt record or bad MAC" when first logging in

### ISSUE THREAD

**Issue by TC01** [magne4000/quassel-webserver#160]
When first logging into quassel-webserver, sometimes the following message is displayed and buffers for all the networks I'm part of don't load (specifically, Freenode and all associated channels are missing):

```
"message":"Could not decrypt record or bad MAC.","send":true,"alert":{"level":2,"description":20},"origin":"client"}
```

Backlogs for other channels don't load, and instead the message ```{}``` appears several times in the browser.

Nothing seems to be logged on the server itself, either in apache, quassel-webserver itself, or the quassel core instance.

This is happening on multiple installations of the latest quassel-webserver (not just the [apache one I just set up](https://github.com/magne4000/quassel-webserver/issues/159)) against quassel core versions 0.12.3 and 0.12.4. Refreshing the browser seems to fix it.

**Comment by magne4000** [comment]
Same as #90 still don't know why it happens. I still haven't got this once

**Comment by torkelatgenet** [comment]
I have the same issue, I get it almost all the time. Removing the # at the end of the URL often works.

**Comment by magne4000** [comment]
@torkelatgenet @TC01
 * Do you have the error message also with a wrong login/password ?
 * Could you give me your IRC nicks on freenode so I can give you my open instance of quassel-webserver, to know if you also have the issue with an instance which is not yours ?
 * If I want to be able to debug this, I must find a way to reproduce it. Could one of you give me access to your quassel-webserver URLs (via IRC -> Magne` on freenode) ? I will first try to connect to my core with it (so you must have not block access to other servers).

**Comment by torkelatgenet** [comment]
- No, It happens after a successful login.
- Same as on Github
- If you contact me on freenode.

**Comment by magne4000** [comment]
Could you tell me if with the current version you still encounter the issue (`git pull && npm update`). There as been a new major version of `ws` module which implements websocket, and the last version of quassel-webserver uses it now.

**Comment by TC01** [comment]
I'm afraid I still encounter this issue, even with the latest updates.

My IRC nick is TC01 (though we've corresponded on freenode about this, so I guess you already know that :) ). If you are still in need of an instance to test on, I can configure one of my quassel-webservers to allow access to arbitrary cores temporarily.

**Comment by magne4000** [comment]
In fact the commited version did not fully took into account new `ws` version, current version should.

**Comment by bobobo1618** [comment]
I've pulled and updated and I still frequently get this error. If you like I can email you the URL of my server.

**Comment by magne4000** [comment]
Ok now I'm pretty sure that's not client related at all, it has something to do with the data itself (with SSL core connection enabled).

**Comment by magne4000** [comment]
Also, @bobobo1618 @TC01 @torkelatgenet, could you disable your browsers extensions and see if you still have the issue ?

**Comment by bobobo1618** [comment]
@magne4000, the issue persists on Chrome on Android, which lacks any extension features.

I'll point out that I typically see this error far more frequently on connections I expect to be a little less reliable/consistent, like crowded WiFi or cell. It's unusual to see it on a stable Ethernet connection (although I get that occasionally too).

**Comment by magne4000** [comment]
@bobobo1618 good to know

**Comment by romibi** [comment]
having this issue too …
My Quassel core is mamarleys git ppa … on arm (rpi2 ubuntu mate 15.10)
quassel-webserver is 11 commits behind master
npm version: 3.3.12, node version: v5.1.0
(what additional version infos could be of interest?)

And the not completely loading network list is extreme on Edge on Windows 10 Mobile (Aniversary Update, on a slow old device) … like only every 20th try i get the full list …
On Chrome (52.0.2743.116 m (64-bit), with 20+ open tabs) that message pops up too sometimes … but its not a big issue … and the network list is always complete … i think …
(The few times i tried it on Opera nothing popped up)

I'll update quassel-webserver soon … perhaps something changed? :smile: 
(and this already happened before i asked about that apache setup)

**Comment by magne4000** [comment]
This is still occuring even with last version, and I still don't know how to fix it ...

**Comment by mitchty** [comment]
Hitting this constantly as well today. The normal quassel clients work fine however. This is to a lets encrypt signed ssl endpoint. It has been working fine up until today for some reason, but now I can only see one of three configured servers. And that one doesn't work at all. Tried updating to the latest master as well to no real avail.

I also get when I try to click on a channel this as its trying to retrieve scroll back:
{"line":9299,"column":21,"sourceURL":"https://url.tld/javascripts/libquassel.js"}

I don't know any javascript so I'm of no real help outside of being able to say I have nginx setup to allow TLS 1.2/1.1/1.0 if necessary as fallbacks. Though I have SSL entirely disabled. I also ordered my cipher suites to exclude outdated ciphers as per mostly standard norms. Is there any further logging I can enable? I don't see anything that could point to an issue with an ssl connection issue (nothing in error.log saying TLS handshakes are failing), and access.log only has 200/304 requests for connecting. So I'm stumped as to what to start to look for.

**Comment by magne4000** [comment]
@mitchty this is not a HTTP error, it's related to TLS connection to quasselcore, not TLS connection to your webserver. So you'll find nothing in any logs, it's just the TLS packets received from the core that somehow couldn't be decoded by your browser (through `forge` and `libquassel` library).

The fact that it happened suddenly will perhaps help me understand it. What changed between the moment it worked and the moment it began to throw this error ? Perhaps new Network, new Channel, new PM, new Configuration, etc ?

**Comment by mitchty** [comment]
@magne4000 So your comment made me have quick look at some other things.

I see the issue only with safari 10.0, note this is on El Capitan, not Sierra. With 9.1.3 (11601.78) no issues, chrome whatever the current version is is fine as well, and I didn't test firefox.

But that may mean safari 10 is treating things differently and also that at least for my needs there is a workaround.

And nothing has changed network/configuration/channel/etc.. wise. Just one laptop that got safari 10 installed a while back and rebooted. Thankfully I have another system with an older safari to compare against.

**Comment by magne4000** [comment]
Just released `2.1.0`, with updated dependencies, could some of you see if they still have the issue ?

**Comment by mitchty** [comment]
@magne4000 updated my install and sadly still no joy on safari 10, I'll note I do see this occasionally with chrome as well but as noted above by others refreshing seems to fix it.

http://imgur.com/5cUDCG3

**Comment by alexfornuto** [comment]
I used to hit this error infrequently, and restarting the server usually fixed it. This morning was fine, but this afternoon it started, and restarting / refreshing doesn't seem to help. The only recent change is that my LetsEncrypt cert expired a day or two ago. 

```
{"message":"Could not decrypt record or bad MAC.","send":true,"alert":{"level":2,"description":20},"origin":"client"}
```

**Comment by alexfornuto** [comment]
Update: After properly renewing my LetsEncrypt certificate I no longer have this error. I'm curious as to why it wasn't an issue with the provided snakeoil certs, but was with an expired but otherwise valid cert.

**Comment by blunden** [comment]
Yes, this happens occationally for me too and I usually solve it by restarting the quassel-webserver process but that's not a proper solution of course. I have never recevied this error with the QuasselDroid Android app so it seems to be related to this project or its dependencies.

**Comment by magne4000** [comment]
I still don't have any solution for this. Javascript TLS support through `forge` is probably too recent, so for those of you who have the issue, disable `SSL core connection` on login page if you use HTTPS and your core is on the same host as quassel-webserver.

**Comment by alexfornuto** [comment]
Unfortunately I use this on a separate system to provide support for IRC on my Chromebook, and unencrypted traffic is not an option 😢

**Comment by magne4000** [comment]
For those of you having the issue, how many buffers (total amount) do you have ?

**Comment by magne4000** [comment]
Good intuition this time, with a lot more buffers, I sometime have this error too :champagne:.
Don't know if this is fixable though ... It's inherent to quassel's protocol (you can also have the issue without SSL Core connection enabled, but you'll need a shitload of buffers).
For now, I suggest all of you to cleanup you core's of uneeded buffers if you want to use `quassel-webserver` correctly.

**Comment by mitchty** [comment]
I currently have 30 buffers open across around 3 different irc servers. And indeed i do see it with/without ssl connecting to the core from the quassel web server.

**Comment by magne4000** [comment]
@mitchty do you have a network on which you have several channels with a lot (a lot!) of users ?

**Comment by mitchty** [comment]
@magne4000 yep, on freenode and #emacs would be one @1027 at the moment, #haskell at 1683 is another large channel. Might be a few more, not sure what a lot means in context here but those two are at least 2 of the largest on freenode. I have a few more over 600 users as well.

**Comment by alexfornuto** [comment]
@magne4000 I got this issue when connecting to a host with dozens of buffers, and on a new core connected to two networks, with less than 6 buffers total.

**Comment by magne4000** [comment]
I forgot to ask, @alexfornuto on your new core, you have one of the 6 buffers which have a lot of users too ?

**Comment by alexfornuto** [comment]
Assuming channels count as buffers, then yea. It would be a shame not to be able to lurk in populated channels.

**Comment by magne4000** [comment]
Last commits have brought some optimization:
- in [qtdatastream](https://github.com/magne4000/node-qtdatastream) thanks to @yorickvP
- in [net-browserify-alt](https://github.com/magne4000/net-browserify): now we use [last version of available WebSocket protocol](https://github.com/websockets/ws) (with bufferutil)

And on `dev` branch now we have the following:
- libquassel now uses [forge](https://github.com/digitalbazaar/forge) 0.7.0

With all of those, I would like some of you to tell me if you are less prone to have the issue.

You can switch to dev branch with the following commands
```sh
git checkout dev
rm -fr node_modules
npm install
```

**Comment by mitchty** [comment]
@magne4000 just did an update as per your instructions and the web app worked in the same tab where it was broken after a refresh.

I'll run with it a bit longer to test but thats a good start at least. Thanks for the updates!

**Comment by romibi** [comment]
finally updated … (to dev branch)
had to upgrade node and npm (which was broken after upgrading node)

Still the MAC error when using Win10 Mobile
[![https://gyazo.com/c78f2feacdbe414ae0f2cc82f2e3b552](https://i.gyazo.com/thumb/200/_5224ea5750bb573a61d1a49b6a7570cb-png.jpg)](https://gyazo.com/c78f2feacdbe414ae0f2cc82f2e3b552)
But the first impression feels better … and "Freenode" is shown faster

**Comment by magne4000** [comment]
Still also have it on android with Firefox sometimes

**Comment by tecknojock** [comment]
I get it at times too on the chrome desktop, but I've attributed it to the
fact that occasionally my work net looses connection between me and my
server, little internal hiccups or something.

**Comment by mitchty** [comment]
As a note, been running fine for three weeks with the updates with no issues. Seems to work fine with chrome and safari at least. So the changes at least partially fix things from what I can gather.

**Comment by Aktariel** [comment]
1) Had working installation of quassel-webserver running as root on a t2micro AWS instance
2) cleaned up node, npm, and quasselwebserver as thoroughly as I could
3) reinstalled node, npm, and quassel-webserver properly (created a "quasselweb" user and group. edited the settings-user.js, script/startup, and script/quassel-webserver files with correct values and options).
4) used a self-signed SSL cert in both cases (user root and quasselweb)
5) new installation does *not* work. (I just get a scrolling screen of "Error: write after end" messages, and after clearing them, nothing ever shows up (chat list stays empty, for example).

fwiw, the original installation used the non git-clone method, and the new installation uses the current installation method.

**Comment by magne4000** [comment]
I fixed something in `tls-browserify` which could cause a race condition. Could some of you try to `npm update` and do some tests ?

**Comment by tom3q** [comment]
The update from 8 days ago didn't fix it for me, but after updating yesterday (which ended up fetching a new libquassel) it started to work! Thanks.

**Comment by rodneyrod** [comment]
Reporting the issue is persisting, randomly get 'Error: write after end' errors in Firefox Portable, it causes the web interface to become unresponsive and clicking on other chats in the window just bring up another 'Error: write after end' error.

**Comment by limpkin** [comment]
recently changed ssl certificates and I'm now getting this error, but only on the browser i've always been using (chrome).
Everything works ok on FF

**Comment by duramato** [comment]
Has any progress been made to fix this? It's unusable for me as it is. I can't connect at all to my quassel core.

**Comment by magne4000** [comment]
@duramato Sadly no, I do not have time currently to investigate more on this issue. Any help is welcome.

**Comment by limpkin** [comment]
@duramato : you may do like I did: switch to FF just for that :)
@magne4000 : your tool is amazing, thanks again for the great work
